### ISSUE TITLE
python.get returns error

### ISSUE THREAD

**Issue by shadowleaves** [cjgb/rPython-win#1]
when running the simple code below:

a <- 1:4
python.assign( "a", a )
python.exec( "b = len( a )" )
python.get( "b" )

i get the following error:
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input

debugging into python.get() and I found "ret" variable seems to be empty:

> ret
> [[1]]
> [1] "_r_return"

$not.found.var
[1] 0

$resultado
[1] ""

the code runs very fast and I wonder if python has been successfully called or not on the first place...

system concerned is: Windows 7 x64, python (anaconda distribution) v2.7. I changed the configure.win to point to c:/Anaconda/Libs and c:/Anaconda/Include.

tested on R version 3.0.2 and R version 3.1.1.

**Comment by jranke** [comment]
This code runs fine here, using 32bit R 3.1.2 on Windows 32bit, using Python 2.7.6 from the sourceforge project pywin32.

**Comment by cjgb** [comment]
I submitted a patch today that fixes, I believe, the problem in 64 bit computers. I hope not to have broken it on 32 bit platforms!

**Comment by jranke** [comment]
This code is still running fine on 32bit over here.
