### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by englianhu** [cjgb/rPython-win#4]
`install.packages('rPython', type=source)`
I am using Linux OS and R3.2.1, try to install the package but sounds out of maintenance. Will somebody maintain?

**Comment by englianhu** [comment]
Try to modify `[root@test~]# vim configure.win` but the file is blank since `removing ‘/usr/lib64/R/library/rPython’` after `ERROR: configuration failed for package ‘rPython’`. Any solution?

```
[root@testing~]# python --version
Python 2.7.5
[root@testing~]# python3 --version
Python 3.4.3
[root@testing~]# sudo su - -c "R -e \"install.packages('rPython', repos='http://cran.rstudio.com')\""

R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('rPython', repos='http://cran.rstudio.com')
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/rPython_0.0-5.tar.gz'
Content type 'application/x-gzip' length 37109 bytes (36 KB)
==================================================
downloaded 36 KB

* installing *source* package ‘rPython’ ...
** package ‘rPython’ successfully unpacked and MD5 sums checked
a specific python version to use was not provided
defaulting to the standard python in the system
which: no python-config in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
could not locate python-config
ERROR: configuration failed for package ‘rPython’
* removing ‘/usr/lib64/R/library/rPython’

The downloaded source packages are in
        ‘/tmp/RtmpMd8zVY/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("rPython", repos = "http://cran.rstudio.com") :
  installation of package ‘rPython’ had non-zero exit status
```

**Comment by jranke** [comment]
> install.packages('rPython', repos='http://cran.rstudio.com')
> Installing package into ‘/usr/lib64/R/library’
> (as ‘lib’ is unspecified)
> trying URL 'http://cran.rstudio.com/src/contrib/rPython_0.0-5.tar.gz'
> 
> # Content type 'application/x-gzip' length 37109 bytes (36 KB)
> 
> # 
> 
> downloaded 36 KB
- installing _source_ package ‘rPython’ ...
  *\* package ‘rPython’ successfully unpacked and MD5 sums checked
  a specific python version to use was not provided
  defaulting to the standard python in the system
  which: no python-config in 
  (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
  could not locate python-config

It seems you do not have the development packages for python installed. 
On my Debian system, /usr/bin/python-config is provided by python-dev.

**Comment by englianhu** [comment]
Thanks @jranke ,its works...

**Comment by leezx** [comment]
I also met some problems when install rPython in centos. 
ERROR as follow:
"which: no python2-config"
"ERROR: configuration failed for package ‘rPython’"

Finally, I found there was no python2-config in my centos.
Installing python2-config by "yum install python-devel" perfectly solve this problem.
Thanks.
