### ISSUE TITLE
i get this error instaling the rPython on my windows computer

### ISSUE THREAD

**Issue by ghost** [cjgb/rPython-win#5]
installing _source_ package 'rPython' ...
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'rPython'
- removing 'C:/Users/Denis/Documents/R/win-library/3.2/rPython'

this is after i downloaded the rpython for windows and changed the configure.win file to python 34
Please help

**Comment by jranke** [comment]
If you do not find a way to deal with that problem, have a look at the alternative package
PythonInR which is on CRAN and works nicely for me.

**Comment by ghost** [comment]
Okay. I struggled and finnally I installed it in my R version 3.2.2. Cheers!!

**Comment by kailichen** [comment]
Hi @denohminator, I met the same problem as yours. Can you kindly guide me what you did to solve the problem? Thanks!

**Comment by denohpakni** [comment]
Hi @kailichen kailichen ,this what i did today;
P.S> im running R version 3.3.3

1. install.packages("devtools")
2. library(devtools)
3. Get the rtools.33.exe from (https://cran.r-project.org/bin/windows/Rtools/Rtools33.exe)
4. Install the rtools33.exe on your computer.
5. Download the rpython Zip from (https://github.com/cjgb/rPython-win) and extrct the folder "rPython-win-master"
6. Copy the folder to your R libraries ussually in Documents/R/3.3..etc
7. Rename the folder from "rPython-win-master" to "rPython"
8. run 
           install("C:/Users/denohminator/Documents/R/win-library/3.3/rPython")
9. Done :)

 
Remember to change the back slashes from your windows bar to forward slashes( that was a pain in the bum for me. haha)

**Comment by kailichen** [comment]
Thank you so much @denohminator ! I successfully installed rPython on my windows machine going with your steps!

**Comment by snigdhajaiswal** [comment]
Hi @denohminator, I tried the above steps but it didn't help. 
I am using RStudio version 3.4.3 and Anaconda Python3. I am getting the following error 
Error: Could not find build tools necessary to build rPython
